// 项目构建脚本
buildscript {
    // 定义仓库
    repositories {
        google()
        mavenCentral() // 替换 jcenter()，因为 JCenter 已关闭
        maven { url 'https://jitpack.io' }
    }

    // 定义依赖
    dependencies {
        // Android Gradle 插件版本
        classpath 'com.android.tools.build:gradle:7.2.0'
        // Kotlin 插件版本
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0"
    }
}

// 所有子项目的配置
allprojects {
    repositories {
        google()
        mavenCentral() // 替换 jcenter()，因为 JCenter 已关闭
        maven { url 'https://jitpack.io' }
    }
}

// 清理任务
task clean(type: Delete) {
    delete rootProject.buildDir
}
